name: BetterRecycling
author: MichielProost
main: io.github.michielproost.betterrecycling.BetterRecycling
version: 1.0.2
commands:
  betterrecycling:
    description: BetterRecycling commands
    permission: betterrecycling
    usage: Issue the command by typing /betterrecycling in the console.
    aliases: [recycle]

permissions:
  betterrecycling:
    default: true
  betterrecycling.*:
    default: op
    children:
      betterrecycling.help: true
  betterrecycling.help:
    default: true