name: BetterRecycling
author: MichielProost
main: io.github.michielproost.betterrecycling.BetterRecycling
version: 1.0.0
commands:
  betterrecycling:
    description: Basis for all recycle commands.
    usage: Issue the command by typing /betterrecycling in the console.
    aliases: [br]